apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es01
  labels:
    app: es01
spec:
  version: 7.14.1
  nodeSets:
  - name: master
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
  - name: data
    count: 1
    config:
      node.master: false
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
  - name: client
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true
      xpack.ml.enabled: true
      node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer
        ports:
          - port: 9200 # onde vai ouvir dentro do cluster
            targetPort: 9200 # onde vai ouvir dentro do cluster
            nodePort: 32765
        # selector:
        #   app: es01
