apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: es01
spec:
  version: 7.14.1
  count: 1
  config:
    elasticsearch.hosts:
      - http://52.184.206.239:9200
    elasticsearch.username: elastic
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
          - port: 5601 # onde vai ouvir dentro do cluster
            targetPort: 5601 # onde vai ouvir dentro do cluster
            nodePort: 32766
  secureSettings:
    - secretName: kibana-elasticsearch-credentials
  # elasticsearchRef:
  #   name: es01