apiVersion: v1
kind: Service
metadata:
  name: svc-el
spec:
  type: LoadBalancer
  ports:
    - port: 9200 # onde vai ouvir dentro do cluster
      targetPort: 9200 # onde vai ouvir dentro do cluster
      nodePort: 32765
  selector:
    app: el
