apiVersion: v1
kind: Service
metadata:
  name: svc-kb
spec:
  type: LoadBalancer
  ports:
    - port: 5601 # onde vai ouvir dentro do cluster
      targetPort: 5601 # onde vai ouvir dentro do cluster
      nodePort: 32766
  selector:
    app: kb
